# Generated by Django 4.2.3 on 2023-07-28 19:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('porte', models.CharField(choices=[('MEI', 'Microempreendedor Individual'), ('ME', 'Microempresa'), ('EPP', 'Empresa de Pequeno Porte'), ('EMP', 'Empresa de Médio Porte'), ('GP', 'Grande Empresa')], max_length=30)),
                ('site', models.URLField()),
                ('email', models.EmailField(max_length=100)),
                ('linkedin', models.URLField(verbose_name='LinkedIn')),
                ('instagram', models.URLField()),
                ('logo', models.ImageField(blank=True, upload_to='logos/%Y/%m/%d/')),
                ('banner', models.ImageField(blank=True, upload_to='banners/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=70)),
                ('estado', models.CharField(max_length=70)),
                ('rua', models.CharField(max_length=70)),
                ('bairro', models.CharField(max_length=70)),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('complemento', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('paragrafos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('senioridade', models.CharField(choices=[('ESTAGIARIO', 'Estagiário'), ('TRAINEE', 'Trainee'), ('JUNIOR', 'Júnior'), ('PLENO', 'Pleno'), ('SENIOR', 'Sênior'), ('ESPECIALITA', 'Especialista')], max_length=15)),
                ('modalidade_trabalho', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto'), ('HIBRIDO', 'Híbrido')], max_length=15)),
                ('modalidade_contratacao', models.CharField(choices=[('EFETIVO', 'Efetico (CLT)'), ('APRENDIZ', 'Aprendiz'), ('ESTAGIO', 'Estágio'), ('PJ', 'Pessoa Jurídica (PJ)'), ('TRAINEE', 'Trainee'), ('TEMPORARIO', 'Temporário'), ('FREELANCER', 'Freelancer'), ('TERCEIRO', 'Terceiro'), ('BANCO_TALENTOS', 'Banco de talentos'), ('VOLUNTARIO', 'Voluntário'), ('SOCIO', 'Sócio'), ('SUMMER JOB', 'Summer Job')], max_length=15)),
                ('responsabilidades_atribuicoes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=255), blank=True, size=None)),
                ('requisitos_qualificacoes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=255), blank=True, size=None)),
                ('exclusiva_pcd', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recrutamento.empresa')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Recrutador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recrutamento.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='sobre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recrutamento.sobre'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('NB', 'Não-binário'), ('O', 'Masculino'), ('PNR', 'Prefiro não responder')], max_length=4)),
                ('telefone', models.CharField(max_length=15)),
                ('linkedin', models.URLField(verbose_name='LinkedIn')),
                ('github', models.URLField(verbose_name='GitHub')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recrutamento.endereco')),
                ('curriculo', models.FileField(upload_to='curriculos/', verbose_name='Currículo em PDF')),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
